sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: ljB1VbhwlHDqXalpDDq8N14XXYh7K+6VwG34zN1tHhSQZf3gyxhzxUqcD9cr+ywV+R5EvRt3GXPm7Y6gG+QZPBjOOIsjQCp+H5w+VuAlDgoha2EAjdZuks73jUXu2B31hVy2ltaK3X5vzGlqUz2OVqElGtRCiHT8bQwd7SG2FVY1Gtg4hEecU8g6mmevDFrmp2vj6dw3/8/cboxzZ/zmzIONY9N2wL+q8p/OQvdD0WhA23qIzP+Q07UI/KUw/Zf+ADv85Fb7xj8T3jXqhtuh0vxBH+NrAWrNVkLpa0o/bbYrRbVPExis5zNQMh4HQlK6rWtoGyyc4ABenndIPltju/BlSUTX83LhNdxlgtsW+52Aabj9huMXSwN7F8NT/dIlzG4+dI1wvYSrkdSUMl27GoCK86+Fe/RLuMSQMcGTlmYb/CXXh3bMcpTc2wp+Yym4AB/+sb0rnHEpAfye/73/rvwR/iv3VE5pfnZ5m23EFtwCmVLTbPn0HsX0+a3vmZuhu37nIoi/mM2g/yJasQda6DNJU2DeOI8k173/TWWYlg8Krut/fhhCefFvRAPzlvDqSyKscUahYomvp6uZw7MJglu4yiGGhIB0KZAXo+uhAazxYzA9No19ekQYERJZkyFYJYt5jAzVFhnhraZw2tvilDnjAhg2XK/4asERLcNcCkM=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Paul-Kelver_1334
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy